# Travis CI settings

language: python

python:
  - '3.4'

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python3 -m pytest --doctest-modules --cov-report term-missing --cov .

after_success:
  coveralls
